### ISSUE TITLE
Review README after first release

### ISSUE THREAD

**Issue by kennyadsl** [nebulab/solidus_starter_frontend#83]
After we release the first version, we should review the whole README to update installation instructions and experimental notice

**Comment by agnostic-apollo** [comment]
So based on this, are you close to a first release? Is this still in the experimental phase or has the basic stuff been done? I am going to use solidus to build a store, have to decide whether I should use this as a base or build a frontend with bootstrap 4 myself. The later would of course take a lot of time. Any recommendations? Thanks.

**Comment by kennyadsl** [comment]
Hey @agnostic-apollo! Yes, we are close to a release but be aware that this gem is meant to be used as a template from which you can copy/paste files into your own application. This is what we have almost done with the installer generator here https://github.com/nebulab/solidus_starter_frontend/pull/66. We are using this approach with this gem for a real project that is almost ready but yet not in production and till now it seems to work well. 

Anyway, this is an improvement of the standard frontend provided by Solidus (solidus_frontend) gem in terms of simplification mainly. The idea is to provide a super basic frontend that it's easy to change. Sticking at what is provided here to have an initial version of your store ready soon or using bootstrap 4 really depends on your UI/UX needs and the tools that you and your team are used to work with to speed up development and maintenance. In both cases, this is better than `solidus_frontend` and I'd start from here.

**Comment by agnostic-apollo** [comment]
Hey @kennyadsl, thanks for the quick response. Apologies on my late response, Gmail on android is terrible with notifications.

Anyways, its good to hear that a release is close and its working well for you guys, that means this can indeed be used as a base. Yes, of course files will need to be copy/pasted wherever needed since a custom store would be different. I already got this gem and a local server working yesterday without the installer generator by including following in the Gemfile

```
gem 'solidus_core', '~> 2.10.2'
gem 'solidus_api', '~> 2.10.2'
gem 'solidus_backend', '~> 2.10.2'
gem 'solidus_sample', '~> 2.10.2'
gem 'solidus_auth_devise', '~> 2.2.0'
gem "solidus_starter_frontend", github: 'nebulab/solidus_starter_frontend'
```

and then running

```
bundle
gem update --system
rake db:create
rails g spree:install
rails g solidus_starter_frontend:install
rails g solidus:auth:install
rake railties:install:migrations
rake db:migrate
rails server
```

The UI is much better than the `solidus_frontend`, so great work :)
I'll keep monitoring the progress made here, and pull any updates. And technically there is no team, just me, and I am not really a frontend dev tbh but have been learning for past couple of months and have gotten familiar with bootstrap 4/material design. But since you guys are following a framework agnostic design unlike the bootstrap admin console as far as I can see, will have to figure stuff out along the way and port to bootstrap where ever required. Lot of work to be done.

Thanks again for the response. Really appreciate it.

**Comment by blocknotes** [comment]
@kennyadsl: we added the installation instructions in the README.
Can we close this one?

**Comment by blocknotes** [comment]
README updated by [this one](https://github.com/nebulab/solidus_starter_frontend/pull/110). Closing
